### ISSUE TITLE
Unable to extract word level features on modules04.praat

### ISSUE THREAD

**Issue by pauljskim** [monikaUPF/PyToBI#3]
When I used my textgrid file, word level acoustic features were not extracted. (Phone level seems to be extract well.)

Could you please check and help this problem in my case?

**Comment by monikaUPF** [comment]
Have you checked that your Textgrid with the word segments include boundaries for the first and last word in the Word tier?
Malformed textgrids is the most common source of problems when extracting acoustic features, especially if the functionality works at the phone level.

**Comment by pauljskim** [comment]
In my textgrid file, the labeling at word level does not include the silence period at the beginning and the end. (In the labeling of the phone level, the silence section is included at the beginning and the end, and the acoustic feature is well extracted at the phone level.)

In this case, would it be solved by including the beginning and end silence in word level?

**Comment by monikaUPF** [comment]
It is very likely the issue will be solved by adding beginning and end boundaries in your word tier. In case you still experience issues, do not hesitate to contact me again.
