### ISSUE TITLE
module04.praat not completed

### ISSUE THREAD

**Issue by lilyzihuizhu** [monikaUPF/PyToBI#4]
Hello there, thanks for writing this amazing tool! I was wondering if you could help me with this issue. The Praat scripts mod1-3 have worked perfectly for me so far. However, I got the following error for mod4: 

Error: The command "Set interval text:" does not return anything; not assigned to the string variable "labw$".
Script line 310 not performed or completed:
▒ labw$ = Set interval text: 5, w, labeltextw$ ▒
Script  C:\PyToBI-master\praatScripts\module04.praat  not completed.

I skimmed through the Praat code and found that "labw" was never used else where, so I tried deleting it and changing that line into "Set interval text: 5, w, labeltextw$". This seems to have resolved the Praat issue and I got the output "Prosodic parameters have been successfully computed!" However, I then got the Python error:

Traceback (most recent call last):
  File "C:\PyToBI-master\tobi.py", line 310, in <module>
    iT = TextGridOperations(pathIn, pathOut)
  File "C:\PyToBI-master\tobi.py", line 7, in __init__
    self.textGrid = TextGrid(path)
  File "C:\PyToBI-master\textGrid.py", line 42, in __init__
    self.loadTextGrid(path)
  File "C:\PyToBI-master\textGrid.py", line 53, in loadTextGrid
    start = float(lines[3].split(" = ")[1])
IndexError: list index out of range

I have tried different stimuli from my end and they all resulted in the same issues. I have previously prepped all of my TextGrids using MFL. It would be great if you could help me look into this issue! Thank you for your time and support in advance :)

**Comment by monikaUPF** [comment]
Hello, and thanks for your feedback on this code.

Based on your error, my hypothesis would be that the TextGrid you are using may be malformed as you get an IndexError when trying to save the starting point in line 53 script textGrid.py.

Could you please check that there is a starting boundary interval in your TextGrid?
I'm refering to the value xmin = 0.1 (e.g.) in the intervals from your input TextGrid.

**Comment by lilyzihuizhu** [comment]
Hello there, thanks so much for the quick response! 

Please correct me if I misunderstood your point. I did add an extra 50ms silence both to the beginning and to the end of my audio input. Here's a sample of my stimuli: https://drive.google.com/drive/folders/1A-q1u30hx1xHOWxRMS1jMkhK5iKoLreQ?usp=sharing 

Could you confirm that for mod 4, it is the right thing to do to change line 262 into "Set interval text: 5, w, labeltextw$"? This is where the original problem happened. 

textGrid.py works perfectly for the original Textgrid (test.TextGrid). See below for "lines" after "lines = raw.split("\n")" on line 51.
![image](https://user-images.githubusercontent.com/45474550/140957164-16ed72bf-761c-4717-a616-5189a4d7f16a.png)


I ran the debugger for mod4 Textgrid (test_mod4.TextGrid) and ran into the IndexError since there were extra empty lines after "lines = raw.split("\n")" on line 51.
![image](https://user-images.githubusercontent.com/45474550/140956960-78621abf-915d-4b68-a4a9-2d854b662ba5.png)
 
Appreciate your help!

**Comment by lilyzihuizhu** [comment]
Update: I think the problem was from the IPA symbols in my original TextGrids (as pointed out in one of the closed issues). I made some new TextGrids with MFA using the non-IPA English models and it works now!

Thanks again for this wonderful tool :)
