### ISSUE TITLE
Can not use module04.praat

### ISSUE THREAD

**Issue by a2d8a4v** [monikaUPF/PyToBI#5]
I use Montreal toolkit to generate alignment for both words and phonemes for an utterance, and then use PyToBI toolkit to generate ToBI Labeling. 
However, I encounter the error below, I can not figure out what happens with that.

```
Processing file  19-198-0000.wav
Computing prosodic parameters under Praat

Exporting TextGrid with words and phones alignment
Error: The command "Set interval text:" does not return anything; not assigned to the string variable "labw$".
Script line 310 not performed or completed:
« labw$ = Set interval text: 5, w, labeltextw$ »
Script “path/to/PyToBI/praatScripts//module04.praat” not completed.
Praat: script command <<path/to/PyToBI/praatScripts//module04.praat>> not completed.

```

The data is available [here](https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/example.html#alignment-example) , and I just validated the `19-198-0000` utterance inside the Librispeech corpus.

Thank you for reading

**Comment by monikaUPF** [comment]
I can see in the link the language you might be processing is Mandarin.
The issue you report most likely concerns an encoding issue with the Praat software, not really connected to the PyToBI as such (which was only tested in English as reported in the publication). I would recommend to check Praat's documentation to solve this and adapt PyToBI to the language you want to process.

Thanks in advance for your contributions and for using PyToBI.

**Comment by a2d8a4v** [comment]
@monikaUPF Hi, I use Ubuntu 18.04 as my environment to run Praat (ver 6.2.12, the latest one). And here is the global setting of language:

```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

I also tried your suggestion of using English environment with the settings, but I still got the same error message.

```
export LANG=en_US.UTF-8
export LANGUAGE=
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_ALL=
```

According to the error message,  it seems that `line 262 in module04.praat` do not get the correct return.
And the word inside the `19-198-0000` utterance is English also. Below is the result aligned with the Montreal toolkit.

```
File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0 
xmax = 1.965 
tiers? <exists> 
size = 2 
item []: 
    item [1]:
        class = "IntervalTier" 
        name = "words" 
        xmin = 0 
        xmax = 1.965 
        intervals: size = 4 
        intervals [1]:
            xmin = 0 
            xmax = 0.53 
            text = "" 
        intervals [2]:
            xmin = 0.53 
            xmax = 1.27 
            text = "northanger" 
        intervals [3]:
            xmin = 1.27 
            xmax = 1.77 
            text = "abbey" 
        intervals [4]:
            xmin = 1.77 
            xmax = 1.965 
            text = "" 
    item [2]:
        class = "IntervalTier" 
        name = "phones" 
        xmin = 0 
        xmax = 1.965 
        intervals: size = 12 
        intervals [1]:
            xmin = 0 
            xmax = 0.53 
            text = "" 
        intervals [2]:
            xmin = 0.53 
            xmax = 0.7 
            text = "N" 
        intervals [3]:
            xmin = 0.7 
            xmax = 0.74 
            text = "AO2" 
        intervals [4]:
            xmin = 0.74 
            xmax = 0.84 
            text = "R" 
        intervals [5]:
            xmin = 0.84 
            xmax = 0.91 
            text = "TH" 
        intervals [6]:
            xmin = 0.91 
            xmax = 1.04 
            text = "AE1" 
        intervals [7]:
            xmin = 1.04 
            xmax = 1.13 
            text = "NG" 
        intervals [8]:
            xmin = 1.13 
            xmax = 1.27 
            text = "ER0" 
        intervals [9]:
            xmin = 1.27 
            xmax = 1.46 
            text = "AE1" 
        intervals [10]:
            xmin = 1.46 
            xmax = 1.53 
            text = "B" 
        intervals [11]:
            xmin = 1.53 
            xmax = 1.77 
            text = "IY0" 
        intervals [12]:
            xmin = 1.77 
            xmax = 1.965 
            text = "" 

```

**Comment by a2d8a4v** [comment]
Hi, @monikaUPF, I found a bug in your script. It's not about the running environment for Praat, there is a mistake in module04.praat script.
I commit a new issue for module04.praat script, please check.

**Comment by ZigHello** [comment]
@a2d8a4v I also encountered the same problem as you, how did you solve it?

**Comment by monikaUPF** [comment]
I've checked your fix and it works well, so I've committed the changes to the repo. Thanks for the heads up! and sorry for the inconvenience.

**Comment by a2d8a4v** [comment]
@ZigHello Now you can see the change in the repo. Hope it can help your experiments.
