### ISSUE TITLE
get number = 0 for certain points in the tone tier

### ISSUE THREAD

**Issue by JIE-CHI** [monikaUPF/PyToBI#8]
Thanks for the codes! I was able to label tones and breaks for files with no errors. However, I did notice that sometimes I get several number = 0 in the tone tier. For example:

>         points [16]:
>             number = 10.355
>             mark = "L*+H"
>         points [17]:
>             number = 0
>             mark = "L*"
>         points [18]:
>             number = 10.67
>             mark = "L-L%"
>        .........
>        .........
>         points [53]:
>             number = 39.235
>             mark = "L*"
>         points [54]:
>             number = 0
>             mark = "H*+L"
>         points [55]:
>             number = 0
>             mark = "L*"
>         points [56]:
>             number = 41.72
>             mark = "H*+L"
> 

After running several tests, I discovered that if I modify the line in your code 

https://github.com/monikaUPF/PyToBI/blob/48079ef1453901ab387740ce4ffb70be2f9c84fc/tobi.py#L189

to 

`
if phone and idp == len(ph_inw) - 1: //as the boundary index should be len(ph_inw) - 1`

 I no longer encounter this problem, and the numbers for all the points appear sensible. However, the marks (both tone and breaks) remain unchanged, while the numbers for other points also change compared to the initial results. Therefore, I'm wondering if it's correct to change the code in this way, or if there are alternative solutions to address this issue?

**Comment by JIE-CHI** [comment]
Also as n basically starts from 2 in the following code, why we don't calculate tones for the first word in the sentence? 
#
https://github.com/monikaUPF/PyToBI/blob/48079ef1453901ab387740ce4ffb70be2f9c84fc/tobi.py#L104-L120

**Comment by monikaUPF** [comment]
> Thanks for the codes! I was able to label tones and breaks for files with no errors. However, I did notice that sometimes I get several number = 0 in the tone tier. For example:
> 
> > ```
> >     points [16]:
> >         number = 10.355
> >         mark = "L*+H"
> >     points [17]:
> >         number = 0
> >         mark = "L*"
> >     points [18]:
> >         number = 10.67
> >         mark = "L-L%"
> >    .........
> >    .........
> >     points [53]:
> >         number = 39.235
> >         mark = "L*"
> >     points [54]:
> >         number = 0
> >         mark = "H*+L"
> >     points [55]:
> >         number = 0
> >         mark = "L*"
> >     points [56]:
> >         number = 41.72
> >         mark = "H*+L"
> > ```
> 
> After running several tests, I discovered that if I modify the line in your code
> 
> https://github.com/monikaUPF/PyToBI/blob/48079ef1453901ab387740ce4ffb70be2f9c84fc/tobi.py#L189
> 
> to
> 
> ` if phone and idp == len(ph_inw) - 1: //as the boundary index should be len(ph_inw) - 1`
> 
> I no longer encounter this problem, and the numbers for all the points appear sensible. However, the marks (both tone and breaks) remain unchanged, while the numbers for other points also change compared to the initial results. Therefore, I'm wondering if it's correct to change the code in this way, or if there are alternative solutions to address this issue?

The field "number" refers to the timestamp where the tone annotation is placed considering the start time and end time of the word that is labeled. You can check word boundaries in your TextGrid, as they may be the source of issues, but if modifying the code you get the expected value, then it is perfectly ok.

**Comment by monikaUPF** [comment]
> Also as n basically starts from 2 in the following code, why we don't calculate tones for the first word in the sentence?
> 
> https://github.com/monikaUPF/PyToBI/blob/48079ef1453901ab387740ce4ffb70be2f9c84fc/tobi.py#L104-L120

Word intervals are expected to include a start time and an end time. It is very rare to have a speech sample that contains words at time 0 (unless it is recorded in the wild), that is why we assume that all words include two boundaries: one for the start and one for the end. In order to get a label for a word that starts that early you just need to include a start boundary at a time close to 0. The same logic applies to words at the end of the speech sample.
